/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PangolinERC20 } from "./PangolinERC20";
export * as factories from "./factories";
export { PangolinERC20__factory } from "./factories/PangolinERC20__factory";
