/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as factories from "./factories";

export { Erc20Abi } from "./Erc20Abi";


export { Erc20Abi__factory } from "./factories/Erc20Abi__factory";
