specVersion: "1.0.0"

name: "subquery-example-base-nft"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your
  new Base SubQuery project"
repository: "https://github.com/subquery/subquery-example-base-nft"

schema:
  file: "./schema.graphql"

network:
  # chainId is the EVM Chain ID, for Base Mainnet this is 8453
  # https://chainlist.org/chain/8453
  chainId: "8453"
  # This endpoint must be a public non-pruned archive node
  # We recommend providing more than one endpoint for improved reliability, performance, and uptime
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  endpoint: ["https://mainnet.base.org/", "https://rpc.notadegen.com/base"]
  # Recommended to provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: "https://api.subquery.network/sq/subquery/base-dictionary"

dataSources:
  - kind: ethereum/Runtime # We use ethereum runtime since Base is EVM-compatible
    startBlock: 2155076 # This is the block that the contract was deployed on https://basescan.org/txs?block=0
    options:
      # Must be a key of assets
      abi: erc721base
      address: "0xea2a41c02fa86a4901826615f9796e603c6a4491" # This is the contract address for Bridge To Base NFT Collection 0xea2a41c02fa86a4901826615f9796e603c6a4491
    assets:
      erc721base:
        file: "./abis/erc721base.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleNftClaim
          kind: ethereum/LogHandler # We use ethereum handlers since Base is EVM-compatible
          filter:
            topics:
              ## Follows standard log filters https://docs.ethers.io/v5/concepts/events/
              - TokensClaimed (uint256 claimConditionIndex, address claimer, address receiver, uint256 startTokenId, uint256 quantityClaimed)
              # address: "0x60781C2586D68229fde47564546784ab3fACA982"
